/**
 * Analyze API 테스트
 */

// Mock YouTubeProvider before importing app
jest.mock('../../../src/providers/youtube', () => {
  return {
    YouTubeProvider: jest.fn().mockImplementation(() => ({
      getMetadata: jest.fn(),
    })),
  };
});

// Mock logger
jest.mock('../../../src/utils/logger', () => ({
  logger: {
    debug: jest.fn(),
    info: jest.fn(),
    warn: jest.fn(),
    error: jest.fn(),
    success: jest.fn(),
  },
}));

import { YouTubeProvider } from '../../../src/providers/youtube';
import { app } from '../../../src/api/app';

describe('Analyze API', () => {
  beforeEach(() => {
    jest.clearAllMocks();
  });

  describe('POST /api/v1/analyze', () => {
    const validUrl = 'https://www.youtube.com/watch?v=dQw4w9WgXcQ';

    it('should analyze video with manual captions', async () => {
      const mockMetadata = {
        id: 'dQw4w9WgXcQ',
        title: 'Test Video',
        channel: 'Test Channel',
        duration: 300,
        thumbnail: 'https://i.ytimg.com/vi/dQw4w9WgXcQ/default.jpg',
        availableCaptions: [
          { language: 'en', languageCode: 'en', isAutoGenerated: false },
        ],
        chapters: [
          { title: 'Intro', startTime: 0, endTime: 60 },
          { title: 'Main', startTime: 60, endTime: 240 },
        ],
      };

      (YouTubeProvider as jest.Mock).mockImplementation(() => ({
        getMetadata: jest.fn().mockResolvedValue(mockMetadata),
      }));

      const res = await app.request('/api/v1/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: validUrl }),
      });

      expect(res.status).toBe(200);
      const data = await res.json();

      expect(data.metadata.id).toBe('dQw4w9WgXcQ');
      expect(data.metadata.title).toBe('Test Video');
      expect(data.metadata.channel).toBe('Test Channel');
      expect(data.metadata.duration).toBe(300);
      expect(data.metadata.chapters).toHaveLength(2);
      expect(data.metadata.availableCaptions).toHaveLength(1);

      expect(data.estimate.needsWhisper).toBe(false);
      expect(data.estimate.cost.whisper).toBe(0);
      expect(data.estimate.cost.total).toBe(0);
      expect(data.estimate.processingTime).toBeGreaterThan(0);
    });

    it('should indicate Whisper is needed when no manual captions', async () => {
      const mockMetadata = {
        id: 'dQw4w9WgXcQ',
        title: 'Test Video',
        channel: 'Test Channel',
        duration: 600, // 10 minutes
        thumbnail: 'https://example.com/thumb.jpg',
        availableCaptions: [
          { language: 'en', languageCode: 'en', isAutoGenerated: true },
        ],
      };

      (YouTubeProvider as jest.Mock).mockImplementation(() => ({
        getMetadata: jest.fn().mockResolvedValue(mockMetadata),
      }));

      const res = await app.request('/api/v1/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: validUrl }),
      });

      expect(res.status).toBe(200);
      const data = await res.json();

      expect(data.estimate.needsWhisper).toBe(true);
      expect(data.estimate.cost.whisper).toBeGreaterThan(0);
    });

    it('should handle video with no captions at all', async () => {
      const mockMetadata = {
        id: 'dQw4w9WgXcQ',
        title: 'Test Video',
        channel: 'Test Channel',
        duration: 120,
        thumbnail: 'https://example.com/thumb.jpg',
        availableCaptions: [],
      };

      (YouTubeProvider as jest.Mock).mockImplementation(() => ({
        getMetadata: jest.fn().mockResolvedValue(mockMetadata),
      }));

      const res = await app.request('/api/v1/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: validUrl }),
      });

      expect(res.status).toBe(200);
      const data = await res.json();

      expect(data.estimate.needsWhisper).toBe(true);
    });

    it('should handle video without chapters', async () => {
      const mockMetadata = {
        id: 'dQw4w9WgXcQ',
        title: 'Test Video',
        channel: 'Test Channel',
        duration: 300,
        thumbnail: 'https://example.com/thumb.jpg',
        availableCaptions: [],
        chapters: undefined,
      };

      (YouTubeProvider as jest.Mock).mockImplementation(() => ({
        getMetadata: jest.fn().mockResolvedValue(mockMetadata),
      }));

      const res = await app.request('/api/v1/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: validUrl }),
      });

      expect(res.status).toBe(200);
      const data = await res.json();

      expect(data.metadata.chapters).toBeUndefined();
    });

    it('should return error for invalid URL format', async () => {
      const res = await app.request('/api/v1/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: 'not-a-valid-url' }),
      });

      expect(res.status).toBe(400);
    });

    it('should return error for missing URL', async () => {
      const res = await app.request('/api/v1/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({}),
      });

      expect(res.status).toBe(400);
    });

    it('should return error when YouTube provider fails', async () => {
      (YouTubeProvider as jest.Mock).mockImplementation(() => ({
        getMetadata: jest.fn().mockRejectedValue(new Error('Video not found')),
      }));

      const res = await app.request('/api/v1/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: validUrl }),
      });

      expect(res.status).toBe(400);
      const data = await res.json();
      expect(data.error).toBe('Video not found');
    });

    it('should return default error message when no message in error', async () => {
      (YouTubeProvider as jest.Mock).mockImplementation(() => ({
        getMetadata: jest.fn().mockRejectedValue({}),
      }));

      const res = await app.request('/api/v1/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: validUrl }),
      });

      expect(res.status).toBe(400);
      const data = await res.json();
      expect(data.error).toBe('Failed to analyze video');
    });

    it('should calculate correct processing time estimate', async () => {
      const mockMetadata = {
        id: 'dQw4w9WgXcQ',
        title: 'Test Video',
        channel: 'Test Channel',
        duration: 600, // 10 minutes
        thumbnail: 'https://example.com/thumb.jpg',
        availableCaptions: [{ language: 'en', languageCode: 'en', isAutoGenerated: false }],
      };

      (YouTubeProvider as jest.Mock).mockImplementation(() => ({
        getMetadata: jest.fn().mockResolvedValue(mockMetadata),
      }));

      const res = await app.request('/api/v1/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: validUrl }),
      });

      expect(res.status).toBe(200);
      const data = await res.json();

      // Processing time: 10% of 600 + 30 = 90 seconds
      expect(data.estimate.processingTime).toBe(90);
    });

    it('should include USD currency in cost estimate', async () => {
      const mockMetadata = {
        id: 'dQw4w9WgXcQ',
        title: 'Test Video',
        channel: 'Test Channel',
        duration: 300,
        thumbnail: 'https://example.com/thumb.jpg',
        availableCaptions: [],
      };

      (YouTubeProvider as jest.Mock).mockImplementation(() => ({
        getMetadata: jest.fn().mockResolvedValue(mockMetadata),
      }));

      const res = await app.request('/api/v1/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: validUrl }),
      });

      expect(res.status).toBe(200);
      const data = await res.json();

      expect(data.estimate.cost.currency).toBe('USD');
    });

    it('should support short YouTube URL format', async () => {
      const mockMetadata = {
        id: 'dQw4w9WgXcQ',
        title: 'Test Video',
        channel: 'Test Channel',
        duration: 100,
        thumbnail: 'https://example.com/thumb.jpg',
        availableCaptions: [],
      };

      (YouTubeProvider as jest.Mock).mockImplementation(() => ({
        getMetadata: jest.fn().mockResolvedValue(mockMetadata),
      }));

      const res = await app.request('/api/v1/analyze', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ url: 'https://youtu.be/dQw4w9WgXcQ' }),
      });

      expect(res.status).toBe(200);
    });
  });
});
