/**
 * Test fixtures for chapter structures
 */

import { Chapter } from '../../src/types/index.js';

/**
 * No chapters (undefined)
 */
export const noChapters: undefined = undefined;

/**
 * Empty chapter array
 */
export const emptyChapters: Chapter[] = [];

/**
 * Short video chapters (3-5 minutes total)
 */
export const shortVideoChapters: Chapter[] = [
  { title: 'Intro', startTime: 0, endTime: 30 },
  { title: 'Main Content', startTime: 30, endTime: 150 },
  { title: 'Outro', startTime: 150, endTime: 180 },
];

/**
 * Tutorial-style chapters (15-20 minutes)
 */
export const tutorialChapters: Chapter[] = [
  { title: 'Introduction', startTime: 0, endTime: 120 },
  { title: 'Setup', startTime: 120, endTime: 300 },
  { title: 'Basic Usage', startTime: 300, endTime: 600 },
  { title: 'Advanced Features', startTime: 600, endTime: 900 },
  { title: 'Conclusion', startTime: 900, endTime: 1200 },
];

/**
 * Conference talk chapters (30-45 minutes)
 */
export const conferenceTalkChapters: Chapter[] = [
  { title: 'Opening & Introduction', startTime: 0, endTime: 300 },
  { title: 'Problem Statement', startTime: 300, endTime: 600 },
  { title: 'Current Solutions', startTime: 600, endTime: 900 },
  { title: 'Our Approach', startTime: 900, endTime: 1500 },
  { title: 'Implementation Details', startTime: 1500, endTime: 2100 },
  { title: 'Results & Metrics', startTime: 2100, endTime: 2400 },
  { title: 'Q&A', startTime: 2400, endTime: 2700 },
];

/**
 * Detailed lecture chapters (60-90 minutes)
 */
export const lectureChapters: Chapter[] = [
  { title: '강의 소개', startTime: 0, endTime: 300 },
  { title: '이론적 배경', startTime: 300, endTime: 900 },
  { title: '기초 개념 1: 신경망', startTime: 900, endTime: 1500 },
  { title: '기초 개념 2: 활성화 함수', startTime: 1500, endTime: 2100 },
  { title: '실습 1: 간단한 모델', startTime: 2100, endTime: 3000 },
  { title: '고급 개념: CNN', startTime: 3000, endTime: 3900 },
  { title: '실습 2: 이미지 분류', startTime: 3900, endTime: 4800 },
  { title: '정리 및 Q&A', startTime: 4800, endTime: 5400 },
];

/**
 * Chapters with Korean titles (React tutorial)
 */
export const koreanChapters: Chapter[] = [
  { title: '소개', startTime: 0, endTime: 180 },
  { title: '환경 설정', startTime: 180, endTime: 420 },
  { title: '컴포넌트 기초', startTime: 420, endTime: 720 },
  { title: 'State와 Props', startTime: 720, endTime: 1080 },
  { title: '이벤트 처리', startTime: 1080, endTime: 1380 },
  { title: '마무리', startTime: 1380, endTime: 1500 },
];

/**
 * Interview-style chapters
 */
export const interviewChapters: Chapter[] = [
  { title: 'Introduction', startTime: 0, endTime: 300 },
  { title: 'Background & Career', startTime: 300, endTime: 900 },
  { title: 'Technical Challenges', startTime: 900, endTime: 1500 },
  { title: 'Lessons Learned', startTime: 1500, endTime: 2100 },
  { title: 'Advice for Engineers', startTime: 2100, endTime: 2700 },
  { title: 'Q&A', startTime: 2700, endTime: 3600 },
];

/**
 * Chapters with very short segments (rapid transitions)
 */
export const rapidChapters: Chapter[] = [
  { title: 'Intro', startTime: 0, endTime: 30 },
  { title: 'Topic 1', startTime: 30, endTime: 90 },
  { title: 'Topic 2', startTime: 90, endTime: 150 },
  { title: 'Topic 3', startTime: 150, endTime: 210 },
  { title: 'Topic 4', startTime: 210, endTime: 270 },
  { title: 'Topic 5', startTime: 270, endTime: 330 },
  { title: 'Wrap Up', startTime: 330, endTime: 360 },
];

/**
 * Chapters with long segments (deep dives)
 */
export const longChapters: Chapter[] = [
  { title: 'Part 1: Foundations', startTime: 0, endTime: 1800 },
  { title: 'Part 2: Advanced Concepts', startTime: 1800, endTime: 3600 },
  { title: 'Part 3: Real-World Applications', startTime: 3600, endTime: 5400 },
];

/**
 * Auto-generated chapters (based on time intervals)
 * Simulates chapters generated when YouTube doesn't provide them
 */
export const autoGeneratedChapters: Chapter[] = [
  { title: 'Section 1', startTime: 0, endTime: 300 },
  { title: 'Section 2', startTime: 300, endTime: 600 },
  { title: 'Section 3', startTime: 600, endTime: 900 },
  { title: 'Section 4', startTime: 900, endTime: 1200 },
];

/**
 * Chapters with special characters and formatting
 */
export const chaptersWithSpecialChars: Chapter[] = [
  { title: 'Introduction: What is React?', startTime: 0, endTime: 300 },
  { title: 'Part 1 - Setup & Installation', startTime: 300, endTime: 600 },
  { title: 'Components (Functional vs Class)', startTime: 600, endTime: 900 },
  { title: 'Q&A Session', startTime: 900, endTime: 1200 },
];

/**
 * Single chapter (entire video as one chapter)
 */
export const singleChapter: Chapter[] = [
  { title: 'Full Video', startTime: 0, endTime: 600 },
];

/**
 * Helper: Generate chapters based on interval
 */
export function generateChapters(
  totalDuration: number,
  intervalSeconds: number = 300,
  language: 'en' | 'ko' = 'en'
): Chapter[] {
  const chapters: Chapter[] = [];
  const titleTemplates = {
    en: 'Chapter',
    ko: '챕터',
  };

  let currentTime = 0;
  let index = 1;

  while (currentTime < totalDuration) {
    const endTime = Math.min(currentTime + intervalSeconds, totalDuration);
    chapters.push({
      title: `${titleTemplates[language]} ${index}`,
      startTime: currentTime,
      endTime: endTime,
    });
    currentTime = endTime;
    index++;
  }

  return chapters;
}

/**
 * Helper: Get chapter at specific timestamp
 */
export function getChapterAtTime(chapters: Chapter[], timestamp: number): Chapter | undefined {
  return chapters.find((c) => timestamp >= c.startTime && timestamp < c.endTime);
}

/**
 * Helper: Get chapter duration
 */
export function getChapterDuration(chapter: Chapter): number {
  return chapter.endTime - chapter.startTime;
}

/**
 * Helper: Validate chapter structure (no gaps or overlaps)
 */
export function validateChapters(chapters: Chapter[]): boolean {
  if (chapters.length === 0) return true;

  for (let i = 0; i < chapters.length - 1; i++) {
    const current = chapters[i];
    const next = chapters[i + 1];

    // Check for gaps or overlaps
    if (current.endTime !== next.startTime) {
      return false;
    }

    // Check for invalid durations
    if (current.startTime >= current.endTime) {
      return false;
    }
  }

  // Check last chapter
  const last = chapters[chapters.length - 1];
  return last.startTime < last.endTime;
}

/**
 * All chapter fixtures for easy iteration
 */
export const allChapterFixtures = {
  noChapters,
  emptyChapters,
  shortVideoChapters,
  tutorialChapters,
  conferenceTalkChapters,
  lectureChapters,
  koreanChapters,
  interviewChapters,
  rapidChapters,
  longChapters,
  autoGeneratedChapters,
  chaptersWithSpecialChars,
  singleChapter,
};
