/**
 * Test fixtures for VideoMetadata
 */

import { VideoMetadata, CaptionTrack, Chapter, VideoType } from '../../src/types/index.js';

/**
 * Sample caption tracks for testing
 */
export const mockCaptionTracks: {
  korean: CaptionTrack;
  english: CaptionTrack;
  koreanAuto: CaptionTrack;
  englishAuto: CaptionTrack;
} = {
  korean: {
    language: 'Korean',
    languageCode: 'ko',
    isAutoGenerated: false,
  },
  english: {
    language: 'English',
    languageCode: 'en',
    isAutoGenerated: false,
  },
  koreanAuto: {
    language: 'Korean',
    languageCode: 'ko',
    isAutoGenerated: true,
  },
  englishAuto: {
    language: 'English',
    languageCode: 'en',
    isAutoGenerated: true,
  },
};

/**
 * Short video metadata (< 5 minutes)
 * Use case: Quick tutorials, demos
 */
export const shortVideoMetadata: VideoMetadata = {
  id: 'short123',
  title: 'Quick TypeScript Tips',
  description: 'Learn 5 essential TypeScript tips in under 3 minutes',
  duration: 180, // 3 minutes
  thumbnail: 'https://i.ytimg.com/vi/short123/maxresdefault.jpg',
  channel: 'Dev Tips',
  uploadDate: '20240115',
  viewCount: 15000,
  availableCaptions: [mockCaptionTracks.english],
  videoType: 'tutorial',
  videoTypeConfidence: 0.85,
};

/**
 * Medium-length video with chapters (10-30 minutes)
 * Use case: Conference talks, detailed tutorials
 */
export const mediumVideoMetadata: VideoMetadata = {
  id: 'medium456',
  title: 'Building Scalable Node.js Applications',
  description:
    'A comprehensive guide to building scalable Node.js applications with best practices and real-world examples.',
  duration: 1200, // 20 minutes
  thumbnail: 'https://i.ytimg.com/vi/medium456/maxresdefault.jpg',
  channel: 'NodeConf',
  uploadDate: '20231020',
  viewCount: 125000,
  availableCaptions: [mockCaptionTracks.english, mockCaptionTracks.englishAuto],
  chapters: [
    { title: 'Introduction', startTime: 0, endTime: 120 },
    { title: 'Architecture Overview', startTime: 120, endTime: 480 },
    { title: 'Performance Optimization', startTime: 480, endTime: 900 },
    { title: 'Deployment Strategies', startTime: 900, endTime: 1200 },
  ],
  videoType: 'conference_talk',
  videoTypeConfidence: 0.92,
};

/**
 * Long video with Korean captions (> 1 hour)
 * Use case: Lectures, in-depth tutorials
 */
export const longVideoMetadata: VideoMetadata = {
  id: 'long789',
  title: '딥러닝 기초부터 실전까지',
  description:
    '딥러닝의 기초 개념부터 실전 프로젝트까지 다루는 종합 강의입니다. TensorFlow와 PyTorch를 활용한 실습 포함.',
  duration: 5400, // 90 minutes
  thumbnail: 'https://i.ytimg.com/vi/long789/maxresdefault.jpg',
  channel: 'AI Academy',
  uploadDate: '20240201',
  viewCount: 45000,
  availableCaptions: [mockCaptionTracks.korean, mockCaptionTracks.koreanAuto],
  chapters: [
    { title: '딥러닝 소개', startTime: 0, endTime: 600 },
    { title: '신경망 기초', startTime: 600, endTime: 1800 },
    { title: 'CNN 구조', startTime: 1800, endTime: 3000 },
    { title: 'RNN과 LSTM', startTime: 3000, endTime: 4200 },
    { title: '실전 프로젝트', startTime: 4200, endTime: 5400 },
  ],
  videoType: 'lecture',
  videoTypeConfidence: 0.95,
};

/**
 * Korean video with multiple caption sources
 * Use case: Testing caption selection logic
 */
export const koreanVideoMetadata: VideoMetadata = {
  id: 'korean123',
  title: 'React 19 새로운 기능 살펴보기',
  description: 'React 19에서 추가된 주요 기능들을 실습과 함께 알아봅니다.',
  duration: 900, // 15 minutes
  thumbnail: 'https://i.ytimg.com/vi/korean123/maxresdefault.jpg',
  channel: 'React Korea',
  uploadDate: '20240110',
  viewCount: 28000,
  availableCaptions: [
    mockCaptionTracks.korean,
    mockCaptionTracks.koreanAuto,
    mockCaptionTracks.english,
  ],
  chapters: [
    { title: '소개', startTime: 0, endTime: 180 },
    { title: 'Server Components', startTime: 180, endTime: 540 },
    { title: 'Actions', startTime: 540, endTime: 900 },
  ],
  videoType: 'tutorial',
  videoTypeConfidence: 0.88,
};

/**
 * Video without chapters
 * Use case: Testing auto-chapter generation
 */
export const noChaptersVideoMetadata: VideoMetadata = {
  id: 'nochap456',
  title: 'Understanding Async/Await',
  description: 'Deep dive into JavaScript async/await patterns',
  duration: 720, // 12 minutes
  thumbnail: 'https://i.ytimg.com/vi/nochap456/maxresdefault.jpg',
  channel: 'JS Mastery',
  uploadDate: '20231215',
  viewCount: 62000,
  availableCaptions: [mockCaptionTracks.english, mockCaptionTracks.englishAuto],
  videoType: 'tutorial',
  videoTypeConfidence: 0.80,
};

/**
 * Video with no available captions
 * Use case: Testing Whisper fallback
 */
export const noCaptionsVideoMetadata: VideoMetadata = {
  id: 'nocap789',
  title: 'Live Coding Session',
  description: 'Building a full-stack app from scratch',
  duration: 2400, // 40 minutes
  thumbnail: 'https://i.ytimg.com/vi/nocap789/maxresdefault.jpg',
  channel: 'Live Coders',
  uploadDate: '20240105',
  viewCount: 8500,
  availableCaptions: [],
  videoType: 'demo',
  videoTypeConfidence: 0.75,
};

/**
 * Interview-style video
 * Use case: Testing video type classification
 */
export const interviewVideoMetadata: VideoMetadata = {
  id: 'interview123',
  title: 'Tech Lead Interview: Scaling at Facebook',
  description: 'An interview with a Facebook tech lead about scaling challenges',
  duration: 1800, // 30 minutes
  thumbnail: 'https://i.ytimg.com/vi/interview123/maxresdefault.jpg',
  channel: 'Tech Talks',
  uploadDate: '20231110',
  viewCount: 95000,
  availableCaptions: [mockCaptionTracks.english],
  chapters: [
    { title: 'Introduction', startTime: 0, endTime: 300 },
    { title: 'Career Journey', startTime: 300, endTime: 900 },
    { title: 'Scaling Challenges', startTime: 900, endTime: 1500 },
    { title: 'Q&A', startTime: 1500, endTime: 1800 },
  ],
  videoType: 'interview',
  videoTypeConfidence: 0.90,
};

/**
 * Conference talk with high view count
 * Use case: Testing popular content handling
 */
export const conferenceVideoMetadata: VideoMetadata = {
  id: 'conf2023',
  title: 'The Future of Web Development - JSConf 2023',
  description:
    'Keynote presentation about the future of web development, covering emerging technologies and trends.',
  duration: 2700, // 45 minutes
  thumbnail: 'https://i.ytimg.com/vi/conf2023/maxresdefault.jpg',
  channel: 'JSConf',
  uploadDate: '20230520',
  viewCount: 350000,
  availableCaptions: [mockCaptionTracks.english, mockCaptionTracks.englishAuto],
  chapters: [
    { title: 'Opening', startTime: 0, endTime: 300 },
    { title: 'Current State of Web Dev', startTime: 300, endTime: 900 },
    { title: 'Emerging Technologies', startTime: 900, endTime: 1800 },
    { title: 'Future Predictions', startTime: 1800, endTime: 2400 },
    { title: 'Q&A', startTime: 2400, endTime: 2700 },
  ],
  videoType: 'conference_talk',
  videoTypeConfidence: 0.98,
};

/**
 * Export all metadata fixtures as array for iteration
 */
export const allVideoMetadata: VideoMetadata[] = [
  shortVideoMetadata,
  mediumVideoMetadata,
  longVideoMetadata,
  koreanVideoMetadata,
  noChaptersVideoMetadata,
  noCaptionsVideoMetadata,
  interviewVideoMetadata,
  conferenceVideoMetadata,
];

/**
 * Helper to get metadata by type
 */
export function getMetadataByType(type: VideoType): VideoMetadata[] {
  return allVideoMetadata.filter((m) => m.videoType === type);
}

/**
 * Helper to get metadata by duration range
 */
export function getMetadataByDuration(minSeconds: number, maxSeconds: number): VideoMetadata[] {
  return allVideoMetadata.filter((m) => m.duration >= minSeconds && m.duration <= maxSeconds);
}
