import { Hono } from 'hono';
import { zValidator } from '@hono/zod-validator';
import { AnalyzeRequestSchema, AnalyzeResponse } from '../models/job';
import { YouTubeProvider } from '../../providers/youtube';
import { CostEstimator } from '../../core/cost-estimator';

const analyze = new Hono();

/**
 * POST /analyze - Analyze video without full conversion
 */
analyze.post('/', zValidator('json', AnalyzeRequestSchema), async (c) => {
  const { url } = c.req.valid('json');

  try {
    const youtube = new YouTubeProvider();
    const metadata = await youtube.getMetadata(url);

    // Calculate cost estimate
    const hasSubtitles = metadata.availableCaptions.some((cap) => !cap.isAutoGenerated);
    const needsWhisper = !hasSubtitles;
    const whisperCost = needsWhisper ? CostEstimator.estimate(metadata.duration).whisperCost : 0;

    // Estimate processing time (rough estimate: 10% of video duration + 30s overhead)
    const processingTime = Math.ceil(metadata.duration * 0.1 + 30);

    const response: AnalyzeResponse = {
      metadata: {
        id: metadata.id,
        title: metadata.title,
        channel: metadata.channel,
        duration: metadata.duration,
        thumbnail: metadata.thumbnail,
        chapters: metadata.chapters?.map((ch) => ({
          title: ch.title,
          startTime: ch.startTime,
          endTime: ch.endTime,
        })),
        availableCaptions: metadata.availableCaptions.map((cap) => ({
          language: cap.language,
          isAutoGenerated: cap.isAutoGenerated,
        })),
      },
      estimate: {
        processingTime,
        cost: {
          whisper: whisperCost,
          total: whisperCost,
          currency: 'USD',
        },
        needsWhisper,
      },
    };

    return c.json(response);
  } catch (error: any) {
    console.error('Analyze error:', error);
    return c.json({ error: error.message || 'Failed to analyze video' }, 400);
  }
});

export { analyze };
