/**
 * Mock Factory - Helper functions to create test data easily
 */

import {
  VideoMetadata,
  SubtitleSegment,
  Chapter,
  Screenshot,
  PDFSection,
  PDFContent,
  ContentSummary,
  CoverMetadata,
  VideoType,
  CaptionTrack,
  SubtitleResult,
  ExecutiveBrief,
  SectionSummary,
} from '../../src/types/index.js';

/**
 * Create a mock VideoMetadata with defaults
 */
export function createMockVideoMetadata(overrides?: Partial<VideoMetadata>): VideoMetadata {
  return {
    id: 'mock123',
    title: 'Mock Video Title',
    description: 'Mock video description',
    duration: 600,
    thumbnail: 'https://i.ytimg.com/vi/mock123/maxresdefault.jpg',
    channel: 'Mock Channel',
    uploadDate: '20240101',
    viewCount: 10000,
    availableCaptions: [
      {
        language: 'English',
        languageCode: 'en',
        isAutoGenerated: false,
      },
    ],
    videoType: 'tutorial',
    videoTypeConfidence: 0.8,
    ...overrides,
  };
}

/**
 * Create mock SubtitleSegment array
 */
export function createMockSubtitles(
  count: number = 5,
  intervalSeconds: number = 5
): SubtitleSegment[] {
  const segments: SubtitleSegment[] = [];
  for (let i = 0; i < count; i++) {
    segments.push({
      start: i * intervalSeconds,
      end: (i + 1) * intervalSeconds,
      text: `Subtitle segment ${i + 1}`,
    });
  }
  return segments;
}

/**
 * Create mock Chapter array
 */
export function createMockChapters(count: number = 3, intervalSeconds: number = 300): Chapter[] {
  const chapters: Chapter[] = [];
  for (let i = 0; i < count; i++) {
    chapters.push({
      title: `Chapter ${i + 1}`,
      startTime: i * intervalSeconds,
      endTime: (i + 1) * intervalSeconds,
    });
  }
  return chapters;
}

/**
 * Create a mock Screenshot
 */
export function createMockScreenshot(overrides?: Partial<Screenshot>): Screenshot {
  return {
    timestamp: 0,
    imagePath: '/tmp/screenshot_0000.jpg',
    width: 1280,
    height: 720,
    ...overrides,
  };
}

/**
 * Create mock Screenshot array
 */
export function createMockScreenshots(
  count: number = 3,
  intervalSeconds: number = 60
): Screenshot[] {
  const screenshots: Screenshot[] = [];
  for (let i = 0; i < count; i++) {
    screenshots.push(
      createMockScreenshot({
        timestamp: i * intervalSeconds,
        imagePath: `/tmp/screenshot_${i.toString().padStart(4, '0')}.jpg`,
      })
    );
  }
  return screenshots;
}

/**
 * Create a mock CaptionTrack
 */
export function createMockCaptionTrack(overrides?: Partial<CaptionTrack>): CaptionTrack {
  return {
    language: 'English',
    languageCode: 'en',
    isAutoGenerated: false,
    ...overrides,
  };
}

/**
 * Create a mock SubtitleResult
 */
export function createMockSubtitleResult(overrides?: Partial<SubtitleResult>): SubtitleResult {
  return {
    source: 'youtube',
    language: 'en',
    segments: createMockSubtitles(5),
    ...overrides,
  };
}

/**
 * Create a mock SectionSummary
 */
export function createMockSectionSummary(overrides?: Partial<SectionSummary>): SectionSummary {
  return {
    summary: 'This section discusses important concepts.',
    keyPoints: ['Key point 1', 'Key point 2', 'Key point 3'],
    mainInformation: {
      paragraphs: ['Detailed information paragraph 1', 'Detailed information paragraph 2'],
      bullets: ['Bullet point 1', 'Bullet point 2'],
    },
    notableQuotes: ['"This is an important quote"', '"Another notable statement"'],
    ...overrides,
  };
}

/**
 * Create a mock PDFSection
 */
export function createMockPDFSection(overrides?: Partial<PDFSection>): PDFSection {
  return {
    timestamp: 0,
    screenshot: createMockScreenshot(),
    subtitles: createMockSubtitles(3),
    sectionSummary: createMockSectionSummary(),
    chapterTitle: 'Introduction',
    ...overrides,
  };
}

/**
 * Create mock PDFSection array
 */
export function createMockPDFSections(count: number = 3): PDFSection[] {
  const sections: PDFSection[] = [];
  for (let i = 0; i < count; i++) {
    sections.push(
      createMockPDFSection({
        timestamp: i * 300,
        screenshot: createMockScreenshot({
          timestamp: i * 300,
          imagePath: `/tmp/screenshot_${i.toString().padStart(4, '0')}.jpg`,
        }),
        chapterTitle: `Section ${i + 1}`,
      })
    );
  }
  return sections;
}

/**
 * Create a mock ContentSummary
 */
export function createMockContentSummary(overrides?: Partial<ContentSummary>): ContentSummary {
  return {
    summary: 'This video covers important topics in software engineering.',
    keyPoints: [
      'Understanding core concepts',
      'Best practices',
      'Real-world applications',
    ],
    language: 'en',
    ...overrides,
  };
}

/**
 * Create a mock CoverMetadata (extended summary)
 */
export function createMockCoverMetadata(overrides?: Partial<CoverMetadata>): CoverMetadata {
  return {
    summary: 'Comprehensive guide to modern web development',
    keyPoints: ['Learn React', 'Master TypeScript', 'Build scalable apps'],
    language: 'en',
    targetAudience: 'Developers, Tech Leads',
    difficulty: 'intermediate',
    prerequisites: ['Basic JavaScript', 'HTML/CSS'],
    estimatedReadTime: 25,
    keywords: ['React', 'TypeScript', 'Web Development'],
    recommendedFor: ['Frontend developers', 'Full-stack engineers'],
    benefits: ['Learn modern tools', 'Improve code quality'],
    ...overrides,
  };
}

/**
 * Create a mock PDFContent
 */
export function createMockPDFContent(overrides?: Partial<PDFContent>): PDFContent {
  return {
    metadata: createMockVideoMetadata(),
    sections: createMockPDFSections(3),
    summary: createMockContentSummary(),
    ...overrides,
  };
}

/**
 * Create a mock ExecutiveBrief
 */
export function createMockExecutiveBrief(overrides?: Partial<ExecutiveBrief>): ExecutiveBrief {
  return {
    title: 'Mock Video Title',
    metadata: {
      channel: 'Mock Channel',
      duration: 1200,
      videoType: 'conference_talk',
      uploadDate: '20240101',
      videoId: 'mock123',
    },
    summary: 'This is a comprehensive 3-5 sentence summary of the video content.',
    keyTakeaways: ['Key takeaway 1', 'Key takeaway 2', 'Key takeaway 3'],
    chapterSummaries: [
      { title: 'Introduction', startTime: 0, summary: 'Overview of the topic' },
      { title: 'Main Content', startTime: 300, summary: 'Detailed discussion' },
      { title: 'Conclusion', startTime: 900, summary: 'Key points and next steps' },
    ],
    actionItems: ['Action item 1', 'Action item 2'],
    ...overrides,
  };
}

/**
 * Create mock video metadata with specific type
 */
export function createMockVideoByType(type: VideoType, duration: number = 1200): VideoMetadata {
  const typeSpecificData: Record<VideoType, Partial<VideoMetadata>> = {
    conference_talk: {
      title: 'The Future of JavaScript - JSConf 2024',
      channel: 'JSConf',
      viewCount: 50000,
    },
    tutorial: {
      title: 'Learn React in 20 Minutes',
      channel: 'Code Academy',
      viewCount: 25000,
    },
    interview: {
      title: 'Tech Lead Interview: Scaling at Scale',
      channel: 'Tech Interviews',
      viewCount: 15000,
    },
    lecture: {
      title: 'Advanced Computer Science Lecture',
      channel: 'University CS',
      viewCount: 8000,
    },
    demo: {
      title: 'Product Demo: New Features',
      channel: 'Product Demos',
      viewCount: 5000,
    },
    discussion: {
      title: 'Panel Discussion: The Future of AI',
      channel: 'Tech Talks',
      viewCount: 12000,
    },
    unknown: {
      title: 'Random Video Content',
      channel: 'Random Channel',
      viewCount: 1000,
    },
  };

  return createMockVideoMetadata({
    videoType: type,
    duration,
    ...typeSpecificData[type],
  });
}

/**
 * Create a complete mock dataset for end-to-end testing
 */
export function createMockE2EDataset(): {
  metadata: VideoMetadata;
  subtitles: SubtitleResult;
  chapters: Chapter[];
  screenshots: Screenshot[];
  pdfContent: PDFContent;
} {
  const metadata = createMockVideoMetadata({
    duration: 900,
    chapters: createMockChapters(3, 300),
  });

  const subtitles = createMockSubtitleResult({
    segments: createMockSubtitles(60, 15),
  });

  const chapters = createMockChapters(3, 300);
  const screenshots = createMockScreenshots(3, 300);

  const pdfContent = createMockPDFContent({
    metadata,
    sections: createMockPDFSections(3),
  });

  return {
    metadata,
    subtitles,
    chapters,
    screenshots,
    pdfContent,
  };
}

/**
 * Create Korean test data
 */
export function createKoreanMockData(): {
  metadata: VideoMetadata;
  subtitles: SubtitleSegment[];
  chapters: Chapter[];
} {
  const metadata = createMockVideoMetadata({
    title: '리액트 훅 완벽 가이드',
    description: '리액트 훅의 모든 것을 다루는 종합 가이드',
    availableCaptions: [
      createMockCaptionTrack({
        language: 'Korean',
        languageCode: 'ko',
      }),
    ],
  });

  const subtitles: SubtitleSegment[] = [
    { start: 0, end: 5, text: '안녕하세요, 오늘은 리액트 훅에 대해 알아보겠습니다.' },
    { start: 5, end: 10, text: 'useState는 가장 기본적인 훅입니다.' },
    { start: 10, end: 15, text: 'useEffect는 부수 효과를 처리합니다.' },
  ];

  const chapters: Chapter[] = [
    { title: '소개', startTime: 0, endTime: 180 },
    { title: '기본 훅', startTime: 180, endTime: 420 },
    { title: '고급 훅', startTime: 420, endTime: 600 },
  ];

  return { metadata, subtitles, chapters };
}

/**
 * Create minimal test data (for performance testing)
 */
export function createMinimalMockData(): PDFContent {
  return {
    metadata: createMockVideoMetadata({ duration: 60 }),
    sections: [
      createMockPDFSection({
        timestamp: 0,
        subtitles: [{ start: 0, end: 60, text: 'Minimal content' }],
      }),
    ],
    summary: createMockContentSummary(),
  };
}

/**
 * Create large test data (for stress testing)
 */
export function createLargeMockData(sectionCount: number = 20): PDFContent {
  return {
    metadata: createMockVideoMetadata({ duration: sectionCount * 300 }),
    sections: createMockPDFSections(sectionCount),
    summary: createMockContentSummary(),
  };
}
